Repository vapor/fluent-postgres-driver, pull requests merged in 2020-06, with the labels that each got.

#156 Support `.dictionary(of:)` data type
  .github/workflows/test.yml
  Package.swift
  Sources/FluentPostgresDriver/PostgresConverterDelegate.swift
  Tests/FluentPostgresDriverTests/FluentPostgresDriverTests.swift
Labels: enhancement, semver-minor

#90 Fix transaction rollback with top-level throw
  Sources/FluentPostgreSQL/PostgreSQLDatabase+TransactionSupporting.swift
  Tests/FluentPostgreSQLTests/FluentPostgreSQLTests.swift
  contribute_boostrap.sh
Labels: bug, semver-patch

#158 2.0.0 release
  .github/CONTRIBUTING.md
  .github/FUNDING.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
  Package.swift
  contribute_boostrap.sh
  docker-compose.yml
  test.Dockerfile
Labels: enhancement
