Repository vapor/fluent-postgres-driver, pull requests merged in 2020-05, with the labels that each got.

#150 Fix macOS CI after GH runners & Homebrew both changed for the worse
  .github/workflows/test.yml
Labels: bug

#151 Register Multiple Databases for FluentBecnhmarker Tests
  .github/workflows/test.yml
  Tests/FluentPostgresDriverTests/FluentPostgresDriverTests.swift
Labels: bug

#152 FluentKit 1.0.0 GM
  .github/workflows/test.yml
  Package.swift
  Sources/FluentPostgresDriver/FluentPostgresDatabase.swift
  Sources/FluentPostgresDriver/FluentPostgresDriver.swift
  Sources/FluentPostgresDriver/PostgresConverterDelegate.swift
  Sources/FluentPostgresDriver/PostgresRow+Database.swift
  Tests/FluentPostgresDriverTests/FluentPostgresDriverTests.swift
  docker-compose.yml
Labels: enhancement, semver-major

#154 Make the tests run with more threads
  Tests/FluentPostgresDriverTests/FluentPostgresDriverTests.swift
Labels: enhancement

#155 Bring the CI workflow in line with the fluent-kit setup
  .github/workflows/test.yml
Labels: enhancement
