Repository vapor/fluent-postgres-driver, pull requests merged in 2022-03, with the labels that each got.

#190 Support adding multiple enum cases at once
  Sources/FluentPostgresDriver/FluentPostgresDatabase.swift
  Tests/FluentPostgresDriverTests/FluentPostgresDriverTests.swift
Labels: semver-patch

#192 Fix logging of enum builder queries
  Sources/FluentPostgresDriver/FluentPostgresDatabase.swift
Labels: bug, semver-patch

#193 Clean up row decoding
  .github/workflows/test.yml
  Sources/FluentPostgresDriver/PostgresRow+Database.swift
Labels: enhancement, semver-patch
